
################################################################################################## 
# SampAndRes.R                                                                                   #      
# Description: It generates training, validation and test sets as follows:                       #
#               1) a training set and a validation set (comprising TSC and / or non-TSC patients)#  
#               are generated for model building and model selection                             #
#              2) a new training set is generated by keeping non-TSC training patients           #
#               and combining TSC training and validation patients                               #
#              3) a test set is generated that does not contain patients appearing in training   #    
#              and validation set                                                                #   
#                                                                                                #
# Input variables :                                                                              #
#             loop : Iterator                                                                    #
# Other Variables :                                                                              #
#            "Tr" in a variable name represents that it is a training set variable               #
#            "Vl" in a variable name represents that it is validation set variable               #
#            "Ts" in a variable name represents that it is a test set  variable                  #
#            "Id" in a variable name represents that it is an index variable                     #                                   
#            "Num" in a variable name represents that it is a number variable                    #
#             Numsplit : Number of splits for processing non-TSC test patients                   #
#                                                                                                #      
#                                                                                                # 
#                                                                                                # 
# Author : Huma Lodhi                                                                            #
# Date :  2014 --                                                                                #
#                                                                                                #
##################################################################################################


#loop <- 3
SampAndRes <- function(loop) {
  
  filenum <- loop
  
  TrIndexFile <- paste(TrIndexFile,filenum,Ext,sep="")
  VlIndexFile <- paste(VlIndexFile,filenum,Ext,sep="")
  
  TSCTrIndexFile <- paste(TSCTrIndexFile,filenum,Ext,sep="")
  TSCVlIndexFile <- paste(TSCVlIndexFile,filenum,Ext,sep="")
  TSCTsIndexFile <- paste(TSCTsIndexFile,filenum,Ext,sep="")

  
################################################################################################## 
#                                                                                                #      
#                                             TSC                                                # 
#                                                                                                #
##################################################################################################


  PtIdTSC <- TSCAgeGender$Id  
  NumPtTSC <- length(PtIdTSC)
  
  TrPerc <- 0.7
  NumTrPtTSC <- round(TrPerc * NumPtTSC)
  NumOtPtTSC <- NumPtTSC - NumTrPtTSC

  VLTSPerc <- 0.5
  NumVlPtTSC <- round(NumOtPtTSC * VLTSPerc)
  NumTsPtTSC <- NumOtPtTSC - NumVlPtTSC
  
  set.seed(SeedV[filenum])
  Index <- sample(1:NumPtTSC)
  
  set.seed(SeedV[filenum])
  TrTSCIndex <- sample(Index,NumTrPtTSC)
  OtTSCIndex <- setdiff(Index,TrTSCIndex)
  
  set.seed(SeedV[filenum])
  VlTSCIndex <- sample(OtTSCIndex,NumVlPtTSC)
  TsTSCIndex <- setdiff(OtTSCIndex,VlTSCIndex)
  
  TrTSCPtId <- PtIdTSC[TrTSCIndex] #234
  VlTSCPtId <- PtIdTSC[VlTSCIndex] #50
  TsTSCPtId <- PtIdTSC[TsTSCIndex] #50
  
  TrVlTSCPtId <- c(TrTSCPtId,VlTSCPtId) #284

  write.table(TrTSCPtId,file=TSCTrIndexFile,quote=FALSE,col.names=FALSE,row.names=FALSE,append=TRUE)
  write.table(VlTSCPtId,file=TSCVlIndexFile,quote=FALSE,col.names=FALSE,row.names=FALSE,append=TRUE) 

  rm(PtIdTSC)



################################################################################################## 
#                                                                                                #      
#                                        non-TSC                                                 # 
#                                                                                                #
##################################################################################################

  
  PtIdNonTSC <- NonTSCAgeGender$Id  
  
  NumPtNonTSC <- length(PtIdNonTSC) #99999
  
  NumTrPtNonTSC <- round(PERC * NumPtNonTSC) #10000
    
  NumOtPtNonTSC <- NumPtNonTSC - NumTrPtNonTSC
  
  NumVlPtNonTSC <- constNumVlPtNonTSC    #20000
  
  NumTsPtNonTSC <- NumOtPtNonTSC - NumVlPtNonTSC   #69999

  if (NumTrPtNonTSC > 0){
    set.seed(SeedV[filenum])
    Index <- sample(1:NumPtNonTSC)
    set.seed(SeedV[filenum])
    TrNonTSCIndex <- sample(Index,NumTrPtNonTSC)
    OtIndex <- setdiff(Index,TrNonTSCIndex)
    TrNonTSCIndex <- sort(TrNonTSCIndex)
  }

  if (NumTrPtNonTSC == 0){
    OtIndex <- sample(1:NumPtNonTSC)
  }

    set.seed(SeedV[filenum])
    VlNonTSCIndex <- sample(OtIndex,NumVlPtNonTSC)
    TsNonTSCIndex <- setdiff(OtIndex,VlNonTSCIndex)

    VlNonTSCIndex <- sort(VlNonTSCIndex)
    TsNonTSCIndex <- sort(TsNonTSCIndex)
  
  if (NumTrPtNonTSC > 0){
    TrNonTSCPtId <- PtIdNonTSC[TrNonTSCIndex]  # 10000
    write.table(TrNonTSCPtId,file=TrIndexFile,quote=FALSE,col.names=FALSE,row.names=FALSE,append=TRUE)    
  }

  VlNonTSCPtId <- PtIdNonTSC[VlNonTSCIndex]  #20000
  
  TsNonTSCPtId <- PtIdNonTSC[TsNonTSCIndex]  #70000
  
  write.table(VlNonTSCPtId,file=VlIndexFile,quote=FALSE,col.names=FALSE,row.names=FALSE,append=TRUE)

  rm(PtIdNonTSC)



################################################################################################## 
#                                                                                                #      
#                           Training set (for validation)                                        # 
#                                                                                                #
##################################################################################################


  cat("\n Processing patients for training\n")

  
  TrTSCAgeGender <- lapply(X=1:1:length(TrTSCPtId), function(X) TSCAgeGender[ which(TSCAgeGender$Id %in% TrTSCPtId[X]), ] )
        
  TrTSCCodeDrug <- lapply(X=1:1:length(TrTSCPtId), function(X) TSCCodeDrug[ which(TSCCodeDrug$V1 %in% TrTSCPtId[X]), ] )
  
  if (NumTrPtNonTSC > 0 & !ONE){

    cat("\n Processing non-TSC training patients\n")
    
    TrNonTSCAgeGender <- lapply(X=1:1:length(TrNonTSCPtId), function(X) NonTSCAgeGender[ which(NonTSCAgeGender$Id %in% TrNonTSCPtId[X]), ] )
    
    TrNonTSCCodeDrug <- lapply(X=1:1:length(TrNonTSCPtId), function(X) NonTSCCodeDrug[ which(NonTSCCodeDrug$V1 %in% TrNonTSCPtId[X]), ] )
    
    TrPtsAgeGender <- c(TrTSCAgeGender,TrNonTSCAgeGender)   #10234=234+10000
  
    rm(list=c('TrNonTSCAgeGender','TrTSCAgeGender'))
    
    TrPtsCodeDrug <- c(TrTSCCodeDrug,TrNonTSCCodeDrug)
    rm(list=c('TrNonTSCCodeDrug','TrTSCCodeDrug'))    
  }

  if (ONE) {
    
    TrPtsAgeGender <- TrTSCAgeGender
    rm(list=c('TrTSCAgeGender'))
    
    TrPtsCodeDrug <- TrTSCCodeDrug
    rm(list=c('TrTSCCodeDrug'))    
  } 
  
##################################################################################################
  
  # Normalise Age

  TrPtsAgeGender <- ldply(TrPtsAgeGender,quickdf)
  
  MeanAgeFirst <- mean(TrPtsAgeGender[,2])
  
  MeanAgeSecond <- mean(TrPtsAgeGender[,3])
    
  TrAgeMat <- NormAge(TrPtsAgeGender,MeanAgeFirst,MeanAgeSecond)


##################################################################################################
  
  # Build drug & code dictionary

  dictFile_ <- paste(dictFile,"_forValidation",filenum,Ext,sep="")
  Dict <- MkDictEnv(TrPtsCodeDrug,dictFile_)   #TrPtsCodeDrug  list[[334]] data.frame[1, 365]


##################################################################################################

  # Feature vectors for patients in training set
  
  TrTSClabel <- rep(1,NumTrPtTSC) # Label (response) vector for TSC patients

  if (!ONE) {
    TrNonTSClabel <- rep(-1,NumTrPtNonTSC) # Label (response) vector for non-TSC patients
    Trlabel <- c(TrTSClabel,TrNonTSClabel)
  }else{ Trlabel <- TrTSClabel}

  Fname <- paste(TrFile1,filenum,Ext,sep="")
  MkFtVec(TrAgeMat,TrPtsCodeDrug,Dict,Trlabel,Fname)

  rm(list=c('TrAgeMat','TrPtsCodeDrug','Trlabel'))
  

################################################################################################## 
#                                                                                                #      
#                                       Validation set                                           # 
#                                                                                                #
##################################################################################################


  cat("\n Processing patients for validation\n")  
  
  VlTSCAgeGender <- lapply(X=1:1:length(VlTSCPtId), function(X) TSCAgeGender[ which(TSCAgeGender$Id %in% VlTSCPtId[X]), ] )
  
  VlTSCCodeDrug <- lapply(X=1:1:length(VlTSCPtId), function(X) TSCCodeDrug[ which(TSCCodeDrug$V1 %in% VlTSCPtId[X]), ] )
  
  VlNonTSCAgeGender <- lapply(X=1:1:length(VlNonTSCPtId), function(X) NonTSCAgeGender[ which(NonTSCAgeGender$Id %in% VlNonTSCPtId[X]), ] )

  VlNonTSCCodeDrug <- lapply(X=1:1:length(VlNonTSCPtId), function(X) NonTSCCodeDrug[ which(NonTSCCodeDrug$V1 %in% VlNonTSCPtId[X]), ] )

  VlPtsCodeDrug <- c(VlTSCCodeDrug,VlNonTSCCodeDrug)

  rm(list=c('VlNonTSCCodeDrug','VlTSCCodeDrug'))

  
##################################################################################################

  # Age normalisation for validation set

  VlPtsAgeGender <- c(VlTSCAgeGender,VlNonTSCAgeGender)
  rm(list=c('VlNonTSCAgeGender','VlTSCAgeGender'))
  VlPtsAgeGender <- ldply(VlPtsAgeGender,quickdf)    
  
  VlAgeMat <- NormAge(VlPtsAgeGender,MeanAgeFirst,MeanAgeSecond)
  
  
##################################################################################################

  # Feature Vectors for patients in validation set
  
  VlTSClabel <- rep(1,NumVlPtTSC) # Label vector for TSC patients invalidation set
  VlNonTSClabel <- rep(-1,NumVlPtNonTSC)  # Label vector for non-TSC patients invalidation set
  Vllabel <- c(VlTSClabel,VlNonTSClabel)
  
  Fname <- paste(VlFile,filenum,Ext,sep="")  

  MkFtVec(VlAgeMat,VlPtsCodeDrug,Dict,Vllabel,Fname)

  rm(list=c('VlAgeMat','VlPtsCodeDrug','VlPtsAgeGender','Vllabel'))
  rm(list=c('Dict'))  



################################################################################################## 
#                                                                                                #      
#                            Training set (for building model to evaluate test data)             # 
#                                                                                                #
##################################################################################################


  cat("\n Processing patients for training\n")
  
  TrTSCPtId <- TrVlTSCPtId
  
  TrTSCAgeGender <- lapply(X=1:1:length(TrTSCPtId), function(X) TSCAgeGender[ which(TSCAgeGender$Id %in% TrTSCPtId[X]), ] )

  TrTSCCodeDrug <- lapply(X=1:1:length(TrTSCPtId), function(X) TSCCodeDrug[ which(TSCCodeDrug$V1 %in% TrTSCPtId[X]), ] )
  
  if (NumTrPtNonTSC > 0 & !ONE){  
    TrNonTSCAgeGender <- lapply(X=1:1:length(TrNonTSCPtId), function(X) NonTSCAgeGender[ which(NonTSCAgeGender$Id %in% TrNonTSCPtId[X]), ] )
    
    TrNonTSCCodeDrug <- lapply(X=1:1:length(TrNonTSCPtId), function(X) NonTSCCodeDrug[ which(NonTSCCodeDrug$V1 %in% TrNonTSCPtId[X]), ] )
    
    TrPtsAgeGender <- c(TrTSCAgeGender,TrNonTSCAgeGender)
    
    rm(list=c('TrNonTSCAgeGender','TrTSCAgeGender'))
    
    TrPtsCodeDrug <- c(TrTSCCodeDrug,TrNonTSCCodeDrug)
    rm(list=c('TrNonTSCCodeDrug'))    
  }
  
  if (ONE) {
    TrPtsAgeGender <- TrTSCAgeGender
    rm(list=c('TrTSCAgeGender'))
    
    TrPtsCodeDrug <- TrTSCCodeDrug
    rm(list=c('TrTSCCodeDrug'))  
  } 
  

##################################################################################################

  # Age normalisation for patients in training set

  TrPtsAgeGender <- ldply(TrPtsAgeGender,quickdf)

  MeanAgeFirst <- mean(TrPtsAgeGender[,2])
  
  MeanAgeSecond <- mean(TrPtsAgeGender[,3])
  
  TrAgeMat <- NormAge(TrPtsAgeGender,MeanAgeFirst,MeanAgeSecond)
  
  
##################################################################################################

  # Drug & Code Dictionary

  dictFile_ <- paste(dictFile,filenum,Ext,sep="")
  Dict <- MkDictEnv(TrPtsCodeDrug,dictFile_)


##################################################################################################

  # Feature Vectors for patients in training set
  
  TrTSClabel <- rep(1,length(TrTSCPtId)) # Label vector for TSC patients

  if (!ONE) 
  {
    TrNonTSClabel <- rep(-1,NumTrPtNonTSC) # Label vector for non-TSC patients
    Trlabel <- c(TrTSClabel,TrNonTSClabel)
  }

  if (ONE)
  {   
    Trlabel <- TrTSClabel  
  }
  
  Fname <- paste(TrFile,filenum,Ext,sep="")

  MkFtVec(TrAgeMat,TrPtsCodeDrug,Dict,Trlabel,Fname)
  rm(list=c('TrAgeMat','TrPtsCodeDrug','Trlabel'))



################################################################################################## 
#                                                                                                #      
#                                       Test set                                                 # 
#                                                                                                #
##################################################################################################


  # TSC patients
  
  TsTSCAgeGender <- lapply(X=1:1:length(TsTSCPtId), function(X) TSCAgeGender[ which(TSCAgeGender$Id %in% TsTSCPtId[X]), ] )
  
  TsTSCCodeDrug <- lapply(X=1:1:length(TsTSCPtId), function(X) TSCCodeDrug[ which(TSCCodeDrug$V1 %in% TsTSCPtId[X]), ] )
  
    
################################################################################################## 
  
  # Age normqlisation for TSC patients in test set 
  
  TsTSCAgeMat <- ldply(TsTSCAgeGender,quickdf)    
  
  TsTSCAgeMat <- NormAge(TsTSCAgeMat,MeanAgeFirst,MeanAgeSecond)
  

################################################################################################## 

  # Feature Vectors for TSC patients in test set
  
  TsTSClabel <- rep(1,NumTsPtTSC) # Label vector for TSC patients in test set
  
  Fname <- paste(TsFilePos,filenum,Ext,sep="")

  MkFtVec(TsTSCAgeMat,TsTSCCodeDrug,Dict,TsTSClabel,Fname)

  rm(list=c('TsTSCAgeMat','TsTSCCodeDrug','TsTSCAgeGender','TsTSClabel'))
  

  #rm(list=c('TSCAgeGender','TSCCode','TSCDrug'))
  
  write.table(TsTSCPtId,file=TSCTsIndexFile,quote=FALSE,col.names=FALSE,row.names=FALSE,append=TRUE)


################################################################################################## 

  # Feature Vectors non-for TSC patients in test set

  cat("\n Processing non-TSC paients for evaluation (test) \n")

  TsIndexFile <- paste(TsIndexFile,filenum,sep="")  

  PARALLEL <- FALSE   # Set PARALLEL to FALSE for swquential processing 

  if (PARALLEL) {
    num_pros <- Sys.getenv('NUMBER_OF_PROCESSORS')
    sfInit(parallel=TRUE, cpus=num_pros, type="SOCK",slaveOutfile = "D:\\RareDisease_TSC\\Data\\FV_2_update/2n/error.log")
    sfLibrary(snowfall)
  }


 # Split non-TSC data and perfrom parallel processing
  cat("\nSplit non-TSC data and perfrom parallel processing\n")
  NumSplit <- 8 

  split <- round(NumTsPtNonTSC/NumSplit)
  IdxAry <- array(list(NULL),NumSplit,split)
cat("\n the initial IdxAry length:", length(IdxAry), '\n')
cat('\n the split num=', NumSplit, ' and the length of each split is ', split, '\n')
  sindex <- 1
  findex <- split

for (j in 1:(NumSplit-1)) {
  LstIdx <- sindex:findex
  TSCLstIdx <- TsNonTSCPtId[LstIdx]
  sindex <- findex + 1
  findex <- findex + split
  IdxAry[[j]] <- list(TSCLstIdx)
}

  LstIdx <- sindex:NumTsPtNonTSC

  TSCLstIdx <- TsNonTSCPtId[LstIdx]

  IdxAry[[j+1]] <- list(TSCLstIdx)
  
  cat("\nindex for split data complete\n")
cat('\n',length(IdxAry),'\n')
#sfExport("IdxAry","Dict","NonTSCAgeGender","NonTSCCodeDrug","MeanAgeFirst","MeanAgeSecond","TsFilePos","TsFileNeg","filenum","TsIndexFile","Ext","norm2")
#the loop has been modified by Jie
SVIdxAry <- sapply(IdxAry,paste,collapse="")
  for(i in 1:NumSplit){
    PrsTst(i, IdxAry, Dict, NonTSCAgeGender, NonTSCCodeDrug, MeanAgeFirst, MeanAgeSecond, TsFilePos, TsFileNeg, filenum, TsIndexFile, Ext, norm2)
  }

}